name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'

      - name: Remove dependencies
        run: rm -rf /node_modules
        working-directory: ./client
      
      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Initialize chmod
        run: chmod +x ./node_modules/.bin/react-scripts
        working-directory: ./client
      
      - name: Run test build
        run: npm run build
        working-directory: ./client
        
      - name: Fix permissions
        run: chmod -R 755 ./node_modules
        working-directory: ./client
        
      - name: Run test lint
        run: npm run lint
        working-directory: ./client

      - name: Run test format write
        run: npm run format:write
        working-directory: ./client

      - name: Run test format:check
        run: npm run format:check
        working-directory: ./client

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job only runs if build passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean Droplet
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
          GH_USER: ${{ secrets.GH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $DO_USER@$DO_HOST << 'EOF'
            cd /PugadMaharlika/Pugad-Maharlika-Frontend
            git remote set-url origin git@github.com:${{ secrets.GH_USER }}/Pugad-Maharlika-Frontend.git
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
