name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install
        working-directory: ./client
        
      - name: Run test build
        run: npm run build
        working-directory: ./client
        
      - name: Run test lint
        run: npm run lint
        working-directory: ./client

      - name: Run test format write
        run: npm run format:write
        working-directory: ./client

      - name: Run test format:check
        run: npm run format:check
        working-directory: ./client

      - name: Deploy
        run: echo "Deploying application..."  # Replace with your deployment command
