name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'

      - name: Run test start
        run: npm start
        
      - name: Run test build
        run: npm run build
        
      - name: Run test lint
        run: npm run lint

      - name: Run test format write
        run: npm run format:write

      - name: Run test format:check
        run: npm run format:write

     
